nicolasbrailo/PianOli

app/src/main/java/com/nicobrailo/pianoli/Piano.java

D6 and D#6 should no longer both play D6.

Fix off-by-one error in Piano.java.initSounds

---

app/src/main/java/com/nicobrailo/pianoli/MainActivity.java
app/src/main/res/values/strings.xml

Reworded:
> Press and hold config icons on black keys to exit.
To:
> Hold the first gear icon, then press the second for options.
*Note:* This wording assumes that #15 is merged (as it uses the word "gear"). But if you don't want to merge #15 then just let me know and I'll update this with more appropriate wording for the spanner icon.
Both my wife and I found it difficult to understand what was happening with the magical second settings button. In hindsight, it makes a lot of sense and is a very clever way to avoid accidental misclicks by curious children.
This extracts the text into a string to allow internationalisation, but also (hopefully) clarifies the behaviour.

Provide mroe explciit instructions to explain the second settings button

---

app/src/main/java/com/nicobrailo/pianoli/AppConfigTrigger.java
app/src/main/java/com/nicobrailo/pianoli/Piano.java
app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java

Changed from constant absolute key sizes. Add at least 7 keys depending on screen size.
If the screen can handle more, they will be the same size as before (220px). Everything
else is based on the resulting key size (e.g. flat key size, settings icon, width of
the bevel on the keys.
To simulate, I intentionally chose an extremely tiny emulator config of 240x432px (vs 1080x1920 as a comparison):
**Existing behaviour**
**Fixed behaviour**
Fixes #18.

Ensure at least 7 (non flat) keys are shown on small devices.

---

app/build.gradle
app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java
fastlane/metadata/android/en-US/changelogs/11.txt

Make a special case for green and yellow which need to be brightened more than others to visually appear distinct, due to their original brightness.
I'll comment back in 30mins or so to let you know how it goes with baby (currently has messy dinner hands).

Brighten coloured keys when pressed, instead of darkening.

---

.gitignore
app/build.gradle
app/src/main/AndroidManifest.xml

Requires target API of 30 or higher, and the main activity must be
exported because it has an <intent-filter>. Also added a new
release flavour with a new application suffix, because somehow
somebody has uploaded the existing package name to GPlay even
though it isn't visible at that package name.

Minor changes to support Google Play publishing.

---

app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java

So, I'm taking a stab at #40 as an MR.
Please be extra careful with this; I didn't even check if this compiles correctly, since I don't have an Android SDK environment set up.
fixes #40
Some interesting test-cases to test the new behaviour:
- "chord moves": touching keys 1+3+5, then sliding all three fingers to 2+4+6.
- should play three notes, where before it only played 1->2
- "finger-switches": touching two *adjacent* keys with one finger each, (e.g 1+2)  
then moving both fingers one to the left/right (2+3).
- 2 remains activated, but since the touch-pointer doing the activating changed, it should play again
- the original test-case:
-  touch key 1, then key 3 with a second finger,
- move the second finger from key 3->4.  
before: didn't play anything  
now: should play note 4.

Correctly handle multi-finger move.

---

app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java

Use the Boomwhacker color convention for coloring the keys.
The Boomwhackers convention is an international convention to color keys (and Boomwhackers) in order to play songs for a non-music reading approach. 
This MR replaces the current key colors by the Boomwhacker colors.
If there are more international convention the colorset should be set in the settings.
Since I am no programmer this MR should be double checked. Never have done a MR before.

Update PianoCanvas.java to the Boomwhacker color convention

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/nicobrailo/pianoli/AboutPreference.java
app/src/main/java/com/nicobrailo/pianoli/AppConfigTrigger.java
app/src/main/java/com/nicobrailo/pianoli/Piano.java
app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java
app/src/main/java/com/nicobrailo/pianoli/Preferences.java
app/src/main/java/com/nicobrailo/pianoli/SettingsFragment.java
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Things to make development easier for ourselves
IntelliJ is a VERY helpful IDE, so might as well do a couple of things it suggests.
1. for personal developer convenience: allow launching the Android Emulator directly into the settings-activity.  
This requires "exporting" the activity, which technically also makes it available to other apps to trigger.
Since this activity doesn't inherently change state, I _think_ this is safe to expose.
- I'm not an Android developer in any way, so please correct me if I overlooked any side effects of this change.
2. Gradle and the Android Gradle Plugin (AGP) have advanced, might as well use the latest versions.
- Gradle 7.5 -> 8.3
- AGP 7.4.2 -> 8.0.2 (the latest I could get working, 8.1.1 isn't compatible apparently?)
3. Build performance IDE …

Tooling Updates and polish

---

app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values/strings.xml
fastlane/metadata/android/de-DE/full_description.txt
fastlane/metadata/android/de-DE/short_description.txt
fastlane/metadata/android/de-DE/title.txt
fastlane/metadata/android/nl-NL/full_description.txt
fastlane/metadata/android/nl-NL/short_description.txt
fastlane/metadata/android/nl-NL/title.txt

I've finally gotten my local native speaker to check my German translation, and boy-howdy, was it needed :sweat_smile: 
This branch 
- adds German :de:  translation
- adds Dutch :netherlands: translations for FastLane stuff, as pointed out in #61 
- sneaks in some finetuning to languages I don't actually speak, but seem reasonable by looking at Wikipedia article titles.

Translations, round 2: NL :netherlands:  polish, add DE :de: 

---

app/build.gradle
app/src/main/java/com/nicobrailo/pianoli/Piano.java
app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java
app/src/main/java/com/nicobrailo/pianoli/melodies/Melody.java
app/src/main/java/com/nicobrailo/pianoli/melodies/MelodyPlayer.java
app/src/main/java/com/nicobrailo/pianoli/melodies/MultipleSongsMelodyPlayer.java
app/src/main/java/com/nicobrailo/pianoli/melodies/NoteMapper.java
app/src/main/java/com/nicobrailo/pianoli/melodies/SingleSongMelodyPlayer.java
app/src/main/java/com/nicobrailo/pianoli/song/ImALittleTeapot.java
app/src/main/java/com/nicobrailo/pianoli/song/InsyWinsySpider.java
app/src/main/java/com/nicobrailo/pianoli/song/TwinkleTwinkleLittleStar.java
app/src/main/java/com/nicobrailo/pianoli/song/WaltzingMatilda.java
app/src/test/java/android/util/Log.java
app/src/test/java/com/nicobrailo/pianoli/melodies/MelodyTest.java
app/src/test/java/com/nicobrailo/pianoli/melodies/NoteMapperTest.java
build.gradle

I'm practicing my refactoring-fu, and have been wanting to try out JUnit5 for ages.  
The result is this branch :smile: 
Please let me know what you think!
It:
- moves song definitions to dedicated files.
- I think this makes contribution of future songs more accessible, as the "template" for a new song becomes disentangled from app-logic.
- extracts all the `String` -> `key_idx` conversion done in `Piano` to a dedicated `NoteMapper`
- as well as the octave-autocompletion that was hidden in `Melody`
- adds JUnit5 so that I could actually write tests for this
- Google only supports JUnit4 natively in their gradle plugin, so I needed to add a community plugin:  
https://github.com/mannodermaus/android-junit5  
I'm not sure how acceptable that is? 
- Convert `Melody` to store already-parsed …

Melody refactor

---

app/src/main/java/com/nicobrailo/pianoli/MainActivity.java
app/src/main/java/com/nicobrailo/pianoli/SettingsActivity.java

When quitting, we accidentally returned to the start and launched the main app again, instead of quitting.
Not sure if it actually fixes #65, but perhaps it has a shot at addressing it. At the least, it fixes a weird behaviour that is worth fixing:
[weird-lock-behaviour.webm](https://github.com/nicolasbrailo/PianOli/assets/248565/c5735e45-bf5a-4c4d-a0b9-bf064d00ff08)

Attempt to fix common crash with pinned mode when not in foreground.

---

app/src/main/java/com/nicobrailo/pianoli/Key.java
app/src/main/java/com/nicobrailo/pianoli/Piano.java
app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java
app/src/test/java/com/nicobrailo/pianoli/KeyContainsTest.java
app/src/test/java/com/nicobrailo/pianoli/PianoTest.java
app/src/test/java/com/nicobrailo/pianoli/PianoUndersizedScreensizeTest.java
app/src/test/java/com/nicobrailo/pianoli/melodies/MelodyTest.java
app/src/test/java/com/nicobrailo/pianoli/melodies/MultipleSongsMelodyPlayerTest.java
app/src/test/java/com/nicobrailo/pianoli/melodies/SingleSongMelodyPlayerTest.java

I've been doing some code-coverage-guided test-writing this weekend.
This unveiled some gaps in my previous `Melody` and `SongPlayer` tests.
I've also started working my way through `Piano`.
It feels a bit dirty, because I had to make some edits to "production" logic, in order to make it testable.  
I've been taught that's normally a big no-no (at work).  
For PianOli, I'm willing to break that rule, since I think it's an intermediate step on the way to move sound-playing to `PianoCanvas`.  
The `Canvas` does all the other Android-API-related stuff, while `Piano` is pure coordinate/state-handling if you ignore sounds.
I'm thinking `Piano` will end up with some kind of Listener-pattern, where both the Canvas and the AppConfigTrigger listen for keydown-events. However, it's still …

More fun with JUnit 5

---

app/build.gradle
fastlane/metadata/android/en-US/changelogs/23.txt

Along with misc chores relating to build scripts, etc, this also includes an attempted fix for #65 and also translations.

Bump for release V1.23 - bugfixes + translations.

---

app/build.gradle
fastlane/metadata/android/en-US/changelogs/24.txt

No changes about translations in this PR, they are all merged automatically by Weblate earlier. This just bumps the version number and adds a release note. For reference: After merging, I manually go to Weblate and make the changelog entry in this PR read only. There is nothing stopping us soliciting translations for these changelogs, however that means that we shouldn't tag a release for a week or two after merging to give time for translations. Given the scale of this app, I think it is not really worth the delay and it is better to just tag after merging this PR. As soon as it is tagged, F-Droid will pick up that commit hash, and thus any future translations will not be included by the subsequent F-Droid build. Hence - no need to translate them and any translations from friendly …

Bump for release V1.24 - Norwegian Bokmål + Polish

---

app/src/main/java/com/nicobrailo/pianoli/AppConfigTrigger.java
app/src/main/java/com/nicobrailo/pianoli/MainActivity.java
app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java
app/src/main/java/com/nicobrailo/pianoli/TooltipReminder.java
app/src/test/java/com/nicobrailo/pianoli/AppConfigTriggerTest.java
app/src/test/java/com/nicobrailo/pianoli/SpyCallback.java
app/src/test/java/com/nicobrailo/pianoli/TooltipReminderTest.java

More holiday hacking! 
This builds on, and includes, the refactoring in #83. That should be reviewed and merged before considering this one. 
This disassembles the different responsibilities of `AppConfigTrigger`, and moves them to new places:
- trigger alert sound moves up to the `MainActivity` callback, so we lose a dependency on the Android context
- Gear-drawing logic moves into `PianoCanvas`, together with all the other draw-calls (completely ridding us of Context) 
- now that we no longer need to mock contexts, the Trigger is suddenly testable! 
- replace the simple `configure shown` boolean with a more powerful "frustration tracker" as brainstormed in #77 
- tracks config-touches in a 5 second window
- resets on any non-config key
- re-shows config toast after 5 config keys (so on …

Holiday hacking 2: Reshow config toast

---

app/src/main/java/com/nicobrailo/pianoli/MainActivity.java
app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java
app/src/main/java/com/nicobrailo/pianoli/SettingsFragment.java
app/src/main/java/com/nicobrailo/pianoli/sound/SampledSoundSet.java
app/src/main/java/com/nicobrailo/pianoli/sound/SoundSet.java
app/src/test/java/com/nicobrailo/pianoli/sound/SpySoundSet.java

I recently learned about Android-API [`StrictMode`](https://developer.android.com/reference/android/os/StrictMode):
> StrictMode is a developer tool which detects things you might be doing by accident and brings them to your attention so you can fix them. 
This builds on my previous "holiday hacking" MRs: #83, #84, so it *appears* giant, but in reality you should only look at the last 4 commits, and only after the previous two were merged)
I've enabled it locally, and ran PianOli in the emulator. There are a few obvious things we can improve:
1. Our config-access Toast was using a non-UI-enabled interface to the application context. It still _worked_ because the runtime context-object also has the UI-interface, but that was by accident, not by design.
We fix it by passing the exact same …

Holiday Hacking 3: Leak hunting with strict mode

---

app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java

Prior to this, it was only doing so in the constructor, so when returning from the settings screen and reinitialising everything, this was omitted. Fixes theme changing.

Fix theme changing by reinitialising preferences each time.

---

app/src/main/java/com/nicobrailo/pianoli/AppConfigTrigger.java
app/src/main/java/com/nicobrailo/pianoli/Piano.java
app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java
app/src/test/java/com/nicobrailo/pianoli/PianoListenerTest.java

Since I'm a perfectionist, and actually already debated some of @pserwylo 's nitpicks with myself:  
improvements as discussed in #83 and #84 
It feels a bit inconsistent to make stronger null-checks on `Piano.addListener()`, but remove them in `AppConfigTrigger`.
Still, I think this is at least per-class-consistent.
The overall null-checking strategy of the App will probably tend to "more strict" as I work my way "outwards" during my refactorings (what, you thought I was done :stuck_out_tongue: :angel: )

Holiday hacking reviews

---

app/src/main/java/com/nicobrailo/pianoli/Theme.java
app/src/main/java/com/nicobrailo/pianoli/melodies/Melody.java
app/src/main/java/com/nicobrailo/pianoli/song/BrotherJohn.java
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/nicobrailo/pianoli/AssertionsExt.java
app/src/test/java/com/nicobrailo/pianoli/DynamicTranslationIdentifierTest.java
app/src/test/java/com/nicobrailo/pianoli/melodies/MelodyTest.java

Ever since @pserwylo added the song-player in #28, I've wanted to add Frère Jacques ("are you sleeping, brother John").
I am 99% sure it has translations for all European languages, as since it definitely has Spanish, English and Chinese, we reach probably 75% of all living humans on the planet.
However, adding songs requires updating quite a few hardcoded strings in multiple places. Since I dislike "you just have to know where" as an answer, especially for open source projects hoping for new contributors, I've added unit tests that check these implicit consistency rules. 
It's definitely not perfect, but I think it covers most cases:

Consistency checks for dynamic strings, before adding "Frère Jacques" song. 

---

app/src/main/java/com/nicobrailo/pianoli/Piano.java
app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java
app/src/main/java/com/nicobrailo/pianoli/Preferences.java
app/src/main/java/com/nicobrailo/pianoli/Theme.java
app/src/test/java/android/graphics/Color.java
app/src/test/java/com/nicobrailo/pianoli/DynamicTranslationIdentifierTest.java
app/src/test/java/com/nicobrailo/pianoli/PreferencesTest.java
app/src/test/java/com/nicobrailo/pianoli/ThemeTest.java

Per discussion in #88 , I think I can make at least the `Theme` reflection there cleaner by making it an Enum instead of a class with static self-constants.  
That can be done as a separate change, which is this PR. If this is acceptable, I'll rebase #88 onto this after it's merged.
While Enum-ifying Theme, I noticed that it's a bit inconsistent that only *big* keys are theme-able.  
Pulling the color-decision for the small/flat keys into Theme as well allows some unification of drawing logic in `PianoCanvas`.  
Right now, flat keys are still hardcoded black, but this improvement means that if we ever want to make colorful flat keys, we need to adapt *only* `Theme`, which satisfies the Single-Responsibility-Principle.
The drawing-simplifications are further aided by making more of the …

Enum-ify `Theme`.

---

app/build.gradle
fastlane/metadata/android/en-US/changelogs/26.txt

Latest SDK required or else GOogle may pull from the play store. Also bumped some minor dependencies for good measure while we are here.

Target sdk 34 and bump to version 1.26
